### ISSUE TITLE
Dashboards to add to projects 

### ISSUE THREAD

**Issue by janagombitova** [akvo/hortinvest#14]
Here is the list of all the Lumen dashboards following the Flow forms. The menu titles should match the dashboard titles. Please note that the dashboards still might change (length) based on feedback from Andrew and Valentine. Their current state is a 1st take. 3 are still empty and to be created but the URLs are already here

Demo Site - https://hortinvest.akvolumen.org/s/7jbe6xb2l1E 
Farmer group - https://hortinvest.akvolumen.org/s/F6UPzdpVkHs 
Cooperatives - https://hortinvest.akvolumen.org/s/aI2UtX3Mhio 
SMEs - https://hortinvest.akvolumen.org/s/yBs6eu3KLzA 
Business cases - https://hortinvest.akvolumen.org/s/534M4nFv6TE 
Fruit tree registration - https://hortinvest.akvolumen.org/s/2X0tZojm71g 
Fruit tree monitoring - https://hortinvest.akvolumen.org/s/eyq63eE0SXM (to be created) 
Production - https://hortinvest.akvolumen.org/s/JEBKlzrgdag 
Sales - https://hortinvest.akvolumen.org/s/ZIXUeTwIBYo 
Meetings - https://hortinvest.akvolumen.org/s/d6pZ0NRyMnU (empty) 
Training - https://hortinvest.akvolumen.org/s/NRuVFl77ijM (empty)

**Comment by kardan** [comment]
For all of these, we need to get the height of the shared dashboard (can be seen in the embed code) once we're "done" with them. Hence would be great if we get a signal once they are done done? Does this make sense?

**Comment by kardan** [comment]
@iperdomo suggested that we could possibly use https://github.com/davidjbradshaw/iframe-resizer to handle iframe heights. Also testing with BrowserStack would be great.

**Comment by kardan** [comment]
I have not had time to add the iframe-resizer.

**Comment by kardan** [comment]
Now available a thttps://hortinvest.akvotest.org/#/project
