### ISSUE TITLE
Menu improvements 

### ISSUE THREAD

**Issue by janagombitova** [akvo/hortinvest#18]
Perhaps this is handled in another issue, or you guys decided on something else, so please comment and close if my issue is irrelevant. 

I have 2 requests for the menu: 

## 1) Remove dropdown for Projects 

The menu is inconsistent at the moment. In Results, we have a menu and a submenu (2 lines) where in Projects we show the options as a dropdown. We should have the navigation the same for both pages 

## 2) Free both rows 

Right now only the main menu row is frozen/fixed in view when scrolling. Is it possible to have both menu lines act this way?

**Comment by kardan** [comment]
@janagombitova there is a new menu that hopefully follows the designs better.

**Comment by kardan** [comment]
Closing this. If there are issues please open a new.
