### ISSUE TITLE
Change order and title of one dashboard

### ISSUE THREAD

**Issue by janagombitova** [akvo/hortinvest#25]
Based on the feedback received from the team: https://docs.google.com/document/d/1KWmnGBD6fARN76jeLqrvwKWdvV_jl612jzKTxCcvCP4/edit 

We were asked to change the title of the dashboard `SMEs` to `Other SMEs` and switch the order to have `Cooperatives`, `Business cases`, `Other SMEs`. 

Jana will adjust the title of the dashboard in Lumen

**Comment by janagombitova** [comment]
Dashboard changes made ;)

**Comment by janagombitova** [comment]
<img width="887" alt="Screenshot 2021-03-30 at 16 20 48" src="https://user-images.githubusercontent.com/12456965/113004441-e5f16080-9173-11eb-9843-1d26b50a0069.png">

Going through the test instance and I noticed that you still need to: 
* Change the submenu tab to `Other SMEs`
* Change the order to: Demo Site, Farmer group, Cooperatives, Business cases, Other SMEs, ...

**Comment by kardan** [comment]
I totally missed this :-(

**Comment by kardan** [comment]
Now in production
