### ISSUE TITLE
Visually make a distinction between target and actual values and %

### ISSUE THREAD

**Issue by janagombitova** [akvo/hortinvest#28]
![Screenshot 2021-03-18 at 16 00 22](https://user-images.githubusercontent.com/12456965/111647778-0e3b9f80-8803-11eb-8a7a-9a4eec975f00.png)

In the current UI it is not clear what is the `target value` and what is the `actual` one. The actual value is the one on top, but we received feedback the difference between the 2 can be somehow made more clear. We do not need to add the word target and actual value to each row as that will clutter the screen but putting more prominence on the `actual value` might do the trick. 

Secondly, we were asked to add more colour to the Results page. After investigating it seems they want to have it more visible how each indicator is doing. It seems the current small coloured dot does not do the trick.

**Comment by Kiarii** [comment]
we could do a font styling for the actual and incl. a key on the menu, to communicate the Actual Vs Target e.g: https://www.figma.com/proto/1BjBzZgref5SzHCwtkEBMn/SNV-Hortinvest-v2?node-id=496%3A182&viewport=4283%2C2612%2C1&scaling=min-zoom&page-id=0%3A1 

On making performance more visible, we could try a bigger dot or a rectangle but imo this would over-emphasize the dots in comparison to the rest of the numerical content, which suggests they are not sure/clear on what information is of primary importance on this page.. 🧐

**Comment by janagombitova** [comment]
<img width="690" alt="Screenshot 2021-03-30 at 16 16 42" src="https://user-images.githubusercontent.com/12456965/113003756-521f9480-9173-11eb-970e-33213fbb831f.png">

We went for putting more emphasis on the actual value. I hope the partner agrees that this is a good improvement to keep the page not too cluttered but showcase what is important at the same time ;) closing the issue
